// Shared demo trade data used by Dashboard and Trade Detail pages
// Replace this with real API data once Supabase is connected

export interface DemoTrade {
  id: string
  instrument: string
  direction: string
  lotSize: number
  session?: string
  entryDate: string
  exitDate?: string
  entryPrice: number
  exitPrice?: number
  stopLoss?: number
  takeProfit?: number
  netPnl?: number
  fees?: number
  swap?: number
  riskR?: number
  returnR?: number
  legs: { id: string; order: number; lotSize: number; entryPrice: number; exitPrice?: number; stopLoss?: number; takeProfit?: number }[]
  reflection?: {
    planFollowed: boolean
    intendedPlan?: string
    entryConfluences: string[]
    tradeManagement?: string
    mistakes: string[]
    entryEmotion?: string
    exitEmotion?: string
    notes?: string
  } | null
  charts?: { htfUrl?: string; mtfUrl?: string; ltfUrl?: string } | null
}

export const DEMO_TRADES: DemoTrade[] = [
  {
    id: "1",
    instrument: "EURUSD",
    direction: "Buy",
    lotSize: 1,
    session: "London",
    entryDate: new Date(2026, 8, 3, 9, 15).toISOString(),
    exitDate: new Date(2026, 8, 3, 10, 30).toISOString(),
    entryPrice: 1.08542,
    exitPrice: 1.08961,
    stopLoss: 1.08400,
    takeProfit: 1.09100,
    netPnl: 420,
    fees: -5,
    swap: 0,
    riskR: 1,
    returnR: 2.1,
    legs: [],
    reflection: {
      planFollowed: true,
      intendedPlan: "A+ Setup Checklist",
      entryConfluences: ["LQ Sweep", "HTF POI", "BOS"],
      tradeManagement: "Partial at 1R, move SL to BE",
      mistakes: [],
      entryEmotion: "Confident",
      exitEmotion: "Relieved",
      notes: "Clean setup, waited for confirmation.",
    },
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "2",
    instrument: "XAUUSD",
    direction: "Sell",
    lotSize: 0.5,
    session: "London",
    entryDate: new Date(2026, 8, 3, 14, 0).toISOString(),
    exitDate: new Date(2026, 8, 3, 15, 20).toISOString(),
    entryPrice: 1924.50,
    exitPrice: 1930.10,
    stopLoss: 1921.00,
    netPnl: -180,
    fees: -3,
    swap: 0,
    riskR: 1,
    returnR: -0.9,
    legs: [],
    reflection: {
      planFollowed: false,
      intendedPlan: "A+ Setup Checklist",
      entryConfluences: ["HTF POI"],
      tradeManagement: "Set and forget",
      mistakes: ["FOMO", "Too Early"],
      entryEmotion: "Fearful",
      exitEmotion: "Frustrated",
      notes: "",
    },
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "3",
    instrument: "GBPUSD",
    direction: "Buy",
    lotSize: 2,
    session: "NewYork",
    entryDate: new Date(2026, 8, 5, 14, 30).toISOString(),
    exitDate: new Date(2026, 8, 5, 16, 45).toISOString(),
    entryPrice: 1.26340,
    exitPrice: 1.27012,
    stopLoss: 1.26180,
    takeProfit: 1.27200,
    netPnl: 850,
    fees: -8,
    swap: 0,
    riskR: 1,
    returnR: 4.2,
    legs: [],
    reflection: {
      planFollowed: true,
      intendedPlan: "London Session Plan",
      entryConfluences: ["LQ Sweep", "MTF POI", "Market Shift"],
      tradeManagement: "Let it run to TP",
      mistakes: [],
      entryEmotion: "Calm",
      exitEmotion: "Confident",
      notes: "Best trade of the week. Stayed disciplined.",
    },
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "4",
    instrument: "EURUSD",
    direction: "Sell",
    lotSize: 1,
    session: "London",
    entryDate: new Date(2026, 8, 8, 9, 0).toISOString(),
    exitDate: new Date(2026, 8, 8, 9, 45).toISOString(),
    entryPrice: 1.08780,
    exitPrice: 1.09100,
    netPnl: -320,
    fees: -5,
    swap: 0,
    riskR: 1,
    returnR: -1.6,
    legs: [],
    reflection: {
      planFollowed: false,
      intendedPlan: "A+ Setup Checklist",
      entryConfluences: ["FVG"],
      tradeManagement: "",
      mistakes: ["FOMO", "Moved SL", "No Plan"],
      entryEmotion: "FOMO",
      exitEmotion: "Frustrated",
      notes: "Revenge trade. Broke all my rules.",
    },
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "5",
    instrument: "NAS100",
    direction: "Buy",
    lotSize: 0.1,
    session: "NewYork",
    entryDate: new Date(2026, 8, 10, 15, 0).toISOString(),
    exitDate: new Date(2026, 8, 10, 17, 30).toISOString(),
    entryPrice: 19250,
    exitPrice: 19850,
    netPnl: 1200,
    fees: -10,
    swap: 0,
    riskR: 1,
    returnR: 3.0,
    legs: [],
    reflection: {
      planFollowed: true,
      entryConfluences: ["Support/Resistance", "Session Open", "BOS"],
      mistakes: [],
      entryEmotion: "Disciplined",
      exitEmotion: "Calm",
      notes: "Followed the playbook perfectly.",
      planFollowed: true,
    },
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "6",
    instrument: "EURUSD",
    direction: "Buy",
    lotSize: 1,
    session: "London",
    entryDate: new Date(2026, 8, 15, 10, 0).toISOString(),
    exitDate: new Date(2026, 8, 15, 10, 30).toISOString(),
    entryPrice: 1.08900,
    exitPrice: 1.08750,
    netPnl: -150,
    fees: -5,
    swap: 0,
    riskR: 1,
    returnR: -0.75,
    legs: [],
    reflection: {
      planFollowed: false,
      entryConfluences: [],
      mistakes: ["Revenge Trading", "Impatient"],
      entryEmotion: "Revenge",
      exitEmotion: "Frustrated",
      notes: "",
    },
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "7",
    instrument: "XAUUSD",
    direction: "Buy",
    lotSize: 1,
    session: "Asia",
    entryDate: new Date(2026, 8, 17, 4, 0).toISOString(),
    exitDate: new Date(2026, 8, 17, 7, 30).toISOString(),
    entryPrice: 1918.00,
    exitPrice: 1930.50,
    stopLoss: 1914.00,
    takeProfit: 1932.00,
    netPnl: 640,
    fees: -6,
    swap: 0,
    riskR: 1,
    returnR: 3.2,
    legs: [],
    reflection: {
      planFollowed: true,
      intendedPlan: "A+ Setup Checklist",
      entryConfluences: ["LQ Sweep", "HTF POI", "LTF POI Mitigation"],
      tradeManagement: "Partial at 2R, rest to TP",
      mistakes: [],
      entryEmotion: "Disciplined",
      exitEmotion: "Confident",
      notes: "Asia session gold setup. Very clean.",
    },
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "8",
    instrument: "GBPJPY",
    direction: "Sell",
    lotSize: 0.5,
    session: "London",
    entryDate: new Date(2026, 8, 22, 9, 30).toISOString(),
    exitDate: new Date(2026, 8, 22, 11, 0).toISOString(),
    entryPrice: 188.450,
    exitPrice: 187.850,
    netPnl: 280,
    fees: -4,
    swap: 0,
    riskR: 1,
    returnR: 1.4,
    legs: [],
    reflection: null,
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "9",
    instrument: "EURUSD",
    direction: "Buy",
    lotSize: 1,
    session: "NewYork",
    entryDate: new Date(2026, 8, 24, 14, 0).toISOString(),
    exitDate: new Date(2026, 8, 24, 14, 45).toISOString(),
    entryPrice: 1.09100,
    exitPrice: 1.09005,
    netPnl: -95,
    fees: -5,
    swap: 0,
    riskR: 1,
    returnR: -0.5,
    legs: [],
    reflection: null,
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
  {
    id: "10",
    instrument: "US500",
    direction: "Buy",
    lotSize: 1,
    session: "NewYork",
    entryDate: new Date(2026, 8, 26, 15, 30).toISOString(),
    exitDate: new Date(2026, 8, 26, 17, 0).toISOString(),
    entryPrice: 5420.00,
    exitPrice: 5458.00,
    stopLoss: 5400.00,
    takeProfit: 5460.00,
    netPnl: 380,
    fees: -8,
    swap: 0,
    riskR: 1,
    returnR: 1.9,
    legs: [],
    reflection: {
      planFollowed: true,
      intendedPlan: "New York Session Plan",
      entryConfluences: ["Support/Resistance", "BOS", "Session Open"],
      tradeManagement: "Trail SL after 1R",
      mistakes: [],
      entryEmotion: "Calm",
      exitEmotion: "Relieved",
      notes: "Good end to the week.",
    },
    charts: { htfUrl: undefined, mtfUrl: undefined, ltfUrl: undefined },
  },
]